# Generated by Django 6.0 on 2025-12-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('channel', models.CharField(help_text='Instagram, Website, WhatsApp, etc.', max_length=50)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
